import { z } from 'zod';

export const transactionSchema = z.object({
  id: z.string().optional(), // Optional: will be generated by the database
  description: z.string().min(2, { message: 'Description must be at least 2 characters.' }),
  amount: z.coerce.number().positive({ message: 'Amount must be a positive number.' }),
  date: z.coerce.date(),
});

export type Transaction = z.infer<typeof transactionSchema>;
